package com.example.asteroidoutpost.sim

import com.example.asteroidoutpost.ai.Vec2

/**
 * Low-level command generated by the autopilot and consumed by movement/weapons.
 */
data class ShipCommand(
    val desiredVelocity: Vec2 = Vec2.ZERO,
    val desiredSpeed: Float = 0f,
    val desiredHeading: Float? = null,
    val desiredAltitude: Float = 0f,
    val fireRequest: FireRequest? = null,
    /** If set, maneuvering thrusters rotate the nose toward this world point
     *  independently of the velocity vector. */
    val targetTracking: Vec2? = null,
    /** Additional lateral acceleration (units/s²) from maneuvering thrusters.
     *  Applied on top of the main velocity update. */
    val lateralImpulse: Vec2 = Vec2.ZERO
)

data class FireRequest(
    val targetId: Int,
    val targetPos: Vec2,
    val targetZ: Float = 0f
)
