#pragma once

#include <stddef.h>
#include <stdint.h>

typedef void* SurfaceHandle;
typedef struct StationEngine StationEngine;
typedef struct StationMesh   StationMesh;
typedef struct StationTexture StationTexture;

#ifdef __cplusplus
extern "C" {
#endif

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

// Create engine instance. Platform-independent — no Android types.
StationEngine* station_engine_create();
void           station_engine_destroy(StationEngine* engine);

// ---------------------------------------------------------------------------
// Shaders — call before surface_created
// Kotlin reads .spv from assets, passes raw bytes here.
// name: "vert" or "frag"
// ---------------------------------------------------------------------------
void station_engine_set_shader(StationEngine* engine,
                               const char*    name,
                               const uint8_t* spv,
                               size_t         length);

// ---------------------------------------------------------------------------
// Surface
// ---------------------------------------------------------------------------
void station_engine_surface_created(StationEngine* engine, SurfaceHandle surface,
                                    int width, int height);
void station_engine_surface_destroyed(StationEngine* engine);
void station_engine_surface_changed(StationEngine* engine, int width, int height);

// ---------------------------------------------------------------------------
// Focus
// ---------------------------------------------------------------------------
void station_engine_resume(StationEngine* engine);
void station_engine_pause(StationEngine* engine);

// ---------------------------------------------------------------------------
// Mesh
// ---------------------------------------------------------------------------
StationMesh* station_engine_load_mesh(StationEngine* engine,
                                      const uint8_t* data, size_t length);
StationMesh* station_engine_load_mesh_colored(StationEngine* engine,
                                              const uint8_t* data, size_t length,
                                              float r, float g, float b);

// E1.3 — upload a procedural mesh from raw vertex + index arrays. Each vertex
// is 10 floats: position(3) + color(4 RGBA) + normal(3). Indices are uint16.
// Use this when you need per-vertex alpha or programmatic geometry that
// doesn't come from a glTF asset (soft-edge nebulae, dome meshes, etc.).
StationMesh* station_engine_load_mesh_raw(StationEngine* engine,
                                          const float*    vertices,
                                          int32_t         vertexCount,
                                          const uint16_t* indices,
                                          int32_t         indexCount);

// E8.4 — same as load_mesh_raw but each vertex is 12 floats including UV:
// pos(3) + rgba(4) + normal(3) + uv(2). Use this for UV-mapped procedural
// meshes (textured quads, sprite billboards, etc.). Existing untextured
// procedural meshes (soft-disk nebulae, dome, fireball) keep using the
// 10-float load_mesh_raw — UV defaults to (0, 0) there.
StationMesh* station_engine_load_mesh_raw_uv(StationEngine* engine,
                                             const float*    vertices,
                                             int32_t         vertexCount,
                                             const uint16_t* indices,
                                             int32_t         indexCount);
void         station_engine_unload_mesh(StationEngine* engine, StationMesh* mesh);
void         station_engine_set_scene_mesh(StationEngine* engine, StationMesh* mesh);

// E8.3 — texture loading. PNG bytes → GPU texture (RGBA8, optimal tiling,
// SHADER_READ_ONLY layout) with a pre-allocated descriptor set ready for
// binding by drawTexturedMesh. Returns 0 / nullptr on decode or upload
// failure (see logs for stbi/Vulkan errors).
StationTexture* station_engine_load_texture(StationEngine* engine,
                                            const uint8_t* pngBytes,
                                            size_t         length);

// E8.4 — upload from raw RGBA8 pixels (4 bytes per pixel, no row padding).
// `length` must equal `width * height * 4`. Use this for procedural
// textures generated by Kotlin (no PNG round-trip required).
StationTexture* station_engine_load_texture_raw(StationEngine* engine,
                                                const uint8_t* rgba8,
                                                int32_t        width,
                                                int32_t        height);
void            station_engine_unload_texture(StationEngine*  engine,
                                              StationTexture* texture);


// ---------------------------------------------------------------------------
// Scene — Kotlin owns the scene, engine just draws what it's told
// ---------------------------------------------------------------------------

// Clear the draw list for the next frame
void station_engine_begin_scene(StationEngine* engine);

// Queue one mesh instance with a model matrix (column-major float[16]).
// E10.3 — `prevModelMatrix` is the matrix this mesh was drawn with on the
// previous frame, used by the vertex shader to compute screen-space
// velocity for motion blur (E10.4 reads the velocity attachment). Pass
// nullptr when no prev tracking exists (engine treats prev = current →
// zero velocity, the natural fallback for static geometry or first-frame
// draws). For moving objects (asteroids, bullets, fireballs), Kotlin
// caches the prev model matrix between frames and supplies it here.
void station_engine_draw_mesh(StationEngine* engine,
                              StationMesh*   mesh,
                              const float    modelMatrix[16],
                              const float    prevModelMatrix[16]);

// Submit the draw list — call once per frame after all draw_mesh calls
void station_engine_draw_pickable_mesh(StationEngine* engine,
                                       StationMesh*   mesh,
                                       int32_t        objectId,
                                       const float    modelMatrix[16],
                                       float          pickRadius,
                                       const float    prevModelMatrix[16]);

void station_engine_draw_billboard_mesh(StationEngine* engine,
                                        StationMesh*   mesh,
                                        float          x,
                                        float          y,
                                        float          z,
                                        float          scale);

// E5.1 — `r,g,b,a` is a per-billboard tint multiplied into the plasma
// fragment heat-ramp. Pass (1,1,1,1) for the default warm-flame look.
// E5.2 — `scaleH, scaleV` lets callers stretch the quad along screen-horizontal
// and screen-vertical independently (streak bullets, flat shockwaves). Pass
// (s, s) for a square billboard.
// E11 — `rotation` (radians) rotates the local mesh around its own Y axis
// before the camera-aligned billboard transform. Lets callers orient
// non-circular plasma meshes (cone fans, streak quads) along an arbitrary
// world direction without authoring per-angle meshes. 0 keeps the legacy
// behaviour (mesh's local +Z maps to screen-up).
// E12 — `lightningSeed` (>0) opts into the lightning-bolt sub-shader —
// the fragment paints a procedural electric arc instead of the heat-ramp
// flame. Seed value is passed through to the shader as `pc.tint.z` to
// decorrelate noise fields between simultaneous bolts. 0 = legacy plasma
// flash (heat-ramp + FBM turbulence).
void station_engine_draw_plasma_billboard(StationEngine* engine,
                                          StationMesh*   mesh,
                                          float          x,
                                          float          y,
                                          float          z,
                                          float          scaleH,
                                          float          scaleV,
                                          float          r,
                                          float          g,
                                          float          b,
                                          float          a,
                                          float          rotation,
                                          float          lightningSeed);

// E8.3 — textured opaque mesh draw. Mesh must have authored UVs; texture
// must come from station_engine_load_texture. (r,g,b,a) is a per-draw
// tint multiplied into the sampled colour (default 1,1,1,1 = no tint).
// E10.3 — `prevModelMatrix` is per-draw motion vector input (see
// station_engine_draw_mesh for semantics).
void station_engine_draw_textured_mesh(StationEngine*  engine,
                                       StationMesh*    mesh,
                                       StationTexture* texture,
                                       const float     modelMatrix[16],
                                       float           r,
                                       float           g,
                                       float           b,
                                       float           a,
                                       const float     prevModelMatrix[16]);

// E9 — instanced particle batch draw. `mesh` is the unit-quad mesh shared
// by every particle (vertex-shader billboards it via per-instance pos).
// `texture` is sampled by the alpha-textured pipeline (smoke/debris) and
// ignored by the additive pipeline (sparks); pass nullptr for additive.
// `instanceFloats` is `count * 8` floats laid out as `pos.xyz, size, rgba`
// per instance. `mode`: 0 = additive (ONE/ONE), 1 = alpha-textured
// (SRC_ALPHA / ONE_MINUS_SRC_ALPHA). Engine drops the tail if `count`
// exceeds the per-pipeline particle budget.
void station_engine_draw_particles(StationEngine*  engine,
                                   StationMesh*    mesh,
                                   StationTexture* texture,
                                   const float*    instanceFloats,
                                   int32_t         count,
                                   int32_t         mode);

// E1.2 — alpha-blended mesh draw. Pipeline uses SRC_ALPHA / ONE_MINUS_SRC_ALPHA
// blending and depth-test on / depth-write off. Mesh's per-vertex alpha
// controls transparency.
// E3.1 — `material` selects a fragment-shader branch: 0 = plain, 1 = nebula
// (FBM noise on alpha), 2 = hex (procedural hex grid on alpha).
void station_engine_draw_translucent_mesh(StationEngine* engine,
                                          StationMesh*   mesh,
                                          const float    modelMatrix[16],
                                          int32_t        material,
                                          const float    prevModelMatrix[16]);

// E7 — additive-blend mesh draw. ONE/ONE additive blend (like plasma
// billboards) but accepts arbitrary 3D meshes via model matrix. Depth-test
// on / depth-write off. Per-vertex alpha controls glow falloff (mesh authors
// put A=1 at glow centres, A=0 at edges); (r,g,b,a) tint multiplies in as
// colour and overall brightness scalar. `material` selects a fragment-shader
// branch: 0 = plain pass-through, 1 = fire (heat-ramp + FBM turbulence +
// Fresnel-like edge soft-fade for spherical fireballs). Used for fireball
// explosions, plasma laser beams, electric arcs.
void station_engine_draw_additive_mesh(StationEngine* engine,
                                       StationMesh*   mesh,
                                       const float    modelMatrix[16],
                                       float          r,
                                       float          g,
                                       float          b,
                                       float          a,
                                       int32_t        material,
                                       const float    prevModelMatrix[16]);

// E14 — laser beam. Dedicated additive pipeline for thin glowing line
// effects between two world-space points. The engine builds a view-aligned
// quad on the GPU (no mesh, no caller-side geometry); the beam fragment
// shader paints a Gaussian core + halo with sharp endpoints and a gentle
// pulse. Public-API contract: works with arbitrary camera poses (the
// vertex shader derives perpendicular from the view matrix, not project
// assumptions). `width` is perpendicular thickness in world units; tint
// is RGBA with alpha as overall brightness. Caller picks any colour;
// the shader doesn't bake a "laser hue" — pass cyan, red, green, etc.
void station_engine_draw_laser_beam(StationEngine* engine,
                                    float startX, float startY, float startZ,
                                    float endX,   float endY,   float endZ,
                                    float width,
                                    float r,      float g,      float b,
                                    float a);

// E20 — force-field shield. Renders the given mesh (a unit hemisphere)
// scaled by `radius` and translated to `(cx, cy, cz)`, through a
// dedicated additive pipeline that combines a fresnel rim glow with up
// to 4 impact blooms (Gaussian falloff at world points). `impacts` is a
// flat array of 16 floats = 4 × (x, y, z, age). Age in [0, 1] is the
// normalised lifetime where 0 = fresh, 1 = expired (sentinel; the
// shader skips the slot). Use 0,0,0,1 to leave a slot empty.
void station_engine_draw_force_field(StationEngine* engine,
                                     StationMesh*   mesh,
                                     float cx, float cy, float cz, float radius,
                                     const float    impacts[16]);

void station_engine_draw_object_frame_mesh(StationEngine* engine,
                                           StationMesh*   frameMesh,
                                           StationMesh*   targetMesh,
                                           const float    modelMatrix[16],
                                           float          padding,
                                           const float    tint[4]);

void station_engine_draw_gameplay_frame_mesh(StationEngine* engine,
                                             StationMesh*   frameMesh,
                                             const float    modelMatrix[16],
                                             const float*   localPoints,
                                             int32_t        pointCount,
                                             float          padding,
                                             float          lineWidth,
                                             const float    tint[4]);

void station_engine_end_scene(StationEngine* engine);

int32_t station_engine_pick_object(StationEngine* engine,
                                   float          screenX,
                                   float          screenY,
                                   int32_t        currentObjectId);

bool station_engine_project_gameplay_bounds(StationEngine* engine,
                                            const float    modelMatrix[16],
                                            const float*   localPoints,
                                            int32_t        pointCount,
                                            float          padding,
                                            float          outBounds[7]);

bool station_engine_project_mesh_bounds(StationEngine* engine,
                                        StationMesh*   mesh,
                                        const float    modelMatrix[16],
                                        float          padding,
                                        float          outBounds[7]);

// ---------------------------------------------------------------------------
// Camera
// ---------------------------------------------------------------------------1
void station_engine_orbit_camera(StationEngine* engine, float deltaYaw, float deltaPitch);
void station_engine_roll_camera(StationEngine* engine, float deltaAngle);
void station_engine_pan_camera(StationEngine* engine, float dx, float dy);
void station_engine_zoom_camera(StationEngine* engine, float factor);
void station_engine_zoom_camera_at(StationEngine* engine,
                                   float factor,
                                   float screenX,
                                   float screenY);
void station_engine_reset_camera(StationEngine* engine);
// E21 — set the camera lookAt target. Used to follow the ship in
// route-mode missions; called each frame from Kotlin.
void station_engine_set_camera_target(StationEngine* engine, float x, float y, float z);

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------
void station_engine_render_frame(StationEngine* engine);

#ifdef __cplusplus
}
#endif
